In [60]:
import pandas as pd
import requests as rq

## Задание 1
Определите, какому фильму было выставлено больше всего оценок 5.0.

In [ ]:
movies_df = pd.read_csv('Файлы к заданию №1/movies.csv')
ratings_df = pd.read_csv('Файлы к заданию №1/ratings.csv')
movies_ra_df  = movies_df.merge(ratings_df,how = 'inner'
                                , left_on='movieId',right_on='movieId')

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [32]:
movies_top_df = movies_ra_df.copy()
movies_top_df = movies_top_df[movies_top_df['rating'] >= 5.0 ]
movies_top_df = movies_top_df.groupby('title')['rating'].count().sort_values(ascending=False).head(1)
movies_top_df

title
Shawshank Redemption, The (1994)    153
Name: rating, dtype: int64

## Задание 2

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. Не учитывайте в расчётах отрицательные значения quantity.

In [36]:
power_df = pd.read_csv('Файлы к заданию №2/power.csv')
transactions_df = pd.read_csv('Файлы к заданию №2/transactions.csv')
display(power_df.head(3))
display(transactions_df.head(3))

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1

   Year  Month    ID Product  Amount  Price  Total  Cost
0  2017      1  t001      A1       7   2904  20328  1200
1  2017      1  t002      A2       2   1896   3792  1100
2  2017      2  t003      A1       5   2904  14520  1200

In [ ]:
power_work_df = power_df.copy()
#power_work_df[power_work_df['country'].str.contains('est', case=False)]['country'].unique()
power_work_df = power_work_df[
                            (power_work_df['country'].isin(['Latvia', 'Lithuania', 'Estonia']))
                            & (power_work_df['quantity'] >= 0) 
                            & (power_work_df['year'] > 2005) 
                            & (power_work_df['year'] <= 2010)
                            & (power_work_df['category'].isin([4, 12, 21]))
                            ]
power_work_df = power_work_df.groupby('country')['quantity'].sum().sort_values(ascending=False)
power_work_df

country
Lithuania    104048.0
Estonia       53188.0
Latvia        46180.0
Name: quantity, dtype: float64

## Задание 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas DataFrame. Вы можете взять любые страницы.

Примеры страниц:

[https://fortrader.org/quotes](https://fortrader.org/quotes)

[pythonworld.ru...strok.html](https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html)

In [64]:
page_url = 'https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html'
hm3_df = pd.read_html(page_url)[0]
hm3_df

,Функция или метод,Назначение
0,"S = 'str'; S = ""str""; S = '''str'''; S = """"""st...",Литералы строк
1,"S = ""s\np\ta\nbbb""",Экранированные последовательности
2,"S = r""C:\temp\new""",Неформатированные строки (подавляют экранирова...
3,"S = b""byte""",Строка байтов
4,S1 + S2,Конкатенация (сложение строк)
5,S1 * 3,Повторение строки
6,S[i],Обращение по индексу
7,S[i:j:step],Извлечение среза
8,len(S),Длина строки
9,"S.find(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пер...
10,"S.rfind(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пос...
11,"S.index(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пер...
12,"S.rindex(str, [start],[end])",Поиск подстроки в строке. Возвращает номер пос...
13,"S.replace(шаблон, замена[, maxcount])",Замена шаблона на замену. maxcount ограничивае...
14,S.split(символ),Разбиение строки по разделителю
15,S.isdigit(),Состоит ли строка из цифр
16,S.isalpha(),Состоит ли строка из букв
17,S.isalnum(),Состоит ли строка из цифр или букв
18,S.islower(),Состоит ли строка из символов в нижнем регистре
19,S.isupper(),Состоит ли строка из символов в верхнем регистре
20,S.isspace(),Состоит ли строка из неотображаемых символов (...
21,S.istitle(),Начинаются ли слова в строке с заглавной буквы
22,S.upper(),Преобразование строки к верхнему регистру
23,S.lower(),Преобразование строки к нижнему регистру
24,S.startswith(str),Начинается ли строка S с шаблона str
25,S.endswith(str),Заканчивается ли строка S шаблоном str
26,S.join(список),Сборка строки из списка с разделителем S
27,ord(символ),Символ в его код ASCII
28,chr(число),Код ASCII в символ
29,S.capitalize(),Переводит первый символ строки в верхний регис...
30,"S.center(width, [fill])","Возвращает отцентрованную строку, по краям кот..."
31,"S.count(str, [start],[end])",Возвращает количество непересекающихся вхожден...
32,S.expandtabs([tabsize]),"Возвращает копию строки, в которой все символы..."
33,S.lstrip([chars]),Удаление пробельных символов в начале строки
34,S.rstrip([chars]),Удаление пробельных символов в конце строки
35,S.strip([chars]),Удаление пробельных символов в начале и в конц...
36,S.partition(шаблон),"Возвращает кортеж, содержащий часть перед перв..."
37,S.rpartition(sep),"Возвращает кортеж, содержащий часть перед посл..."
38,S.swapcase(),"Переводит символы нижнего регистра в верхний, ..."
39,S.title(),Первую букву каждого слова переводит в верхний...
40,S.zfill(width),"Делает длину строки не меньшей width, по необх..."
41,"S.ljust(width, fillchar="" "")","Делает длину строки не меньшей width, по необх..."
42,"S.rjust(width, fillchar="" "")","Делает длину строки не меньшей width, по необх..."
43,"S.format(*args, **kwargs)",Форматирование строки